### ISSUE TITLE
Document Typography Scale on Button

### ISSUE THREAD

**Issue by e111077** [material-components/material-components-web-components#1129]

**Comment by bennypowers** [comment]
Please note that it appears that setting typography sizes on button breaks it's internal layout when an icon is present. The attached screenshot demonstrates changes I made to the (hard-coded) shadow styles in order to acheive a fix in a particular instance:

<img width="1662" alt="Screen Shot 2020-04-19 at 18 53 39" src="https://user-images.githubusercontent.com/1466420/80461465-f8e52a80-893d-11ea-9f99-cb12df268039.png">

**Comment by e111077** [comment]
cc: @asyncLiz 

https://github.com/material-components/material-components-web/issues/5812

**Comment by asyncLiz** [comment]
That issue isn't about the line-height, but the explicit [width, height, and font-size](https://github.com/material-components/material-components-web/blob/39eeaa9873496708025df9dcc1dd7b9d780ab39a/packages/mdc-button/_mixins.scss#L466-L468) specified on icon elements in MDC.

It'd be somewhat related to https://github.com/material-components/material-components-web-components/issues/81 and density, but only if the icons are bigger than 36px. tl;dr, we need to override those lines to use `var(--mdc-icon-size)` as well if it's going to be customizable.
