### ISSUE TITLE
open should be writable property instead of method in snackbar

### ISSUE THREAD

**Issue by sashafirsov** [material-components/material-components-web-components#1212]
**Describe the bug**
When trying to set "open" property to "true" the snackbar does not pop up. 
"open" is a property in majority of MCWC including dynamic pop-ups like menu and dialog. It supports declarative programming via HTML. When replaced with explicit method it breaks possibility of using properties binding for state control and prevents HTML delelopers to pre-render pop-ups when page is opened.

.open() API is 
* inconsistent with overall library design
* prevents pre-defining the state in HTML

**To Reproduce**
1. `<mwc-snackbar labelText="Can't send photo. Retry in 5 seconds." open="true">`
1. open the page
4. snackbar is not opened

**Expected behavior**
snackbar popped up when defined initially or set dynamically by `snackbar.open=true`

**Additional context**
there is a possibility to define a dual API which would override 'open' as a property and keep it a function in same time. But since  majority of MCWC components are using `open` as property, I do not see a need for `open()` as function.

**Comment by asyncLiz** [comment]
It's worth noting that snackbar is different than many other components with a similar `open` property, such as dialog. Those components are persistent: when `open="true"`, they remain open until it is set to false.

Snackbar on the other hand, will automatically dismiss itself after being opened. This can lead to a state mismatch where `open="true"` but the snackbar itself is not open. That's the reason for the usage of a function instead of an attribute in markup, which is inherently more persistent.

**Comment by sashafirsov** [comment]
Kindly disagree. MCWC has been chosen to be on list of supported by CDN libs due to primary web components promise - as extension of HTML. Meaning ability to use declarative programming. So far several libs and most of MCWC components are compliant. 

Menu and Dialog from developer's prospective are not much different from Snackbar. But for some reason are compliant with declarative programming paradigm. Snackbar is not. Should rename this bug to "**compliance with declarative programming**" ? 

That will give a straight answer what principles MCWC is supporting and which in not.  In case of negative answer making the tickets like #812 or enhancement #1181 irrelevant. And MCWC irrelevant for my CDN project and its clients as well.

**Comment by sashafirsov** [comment]
> Snackbar on the other hand, will automatically dismiss itself after being opened. This can lead to a state mismatch where open="true" but the snackbar itself is not open.

What from your statement is not applicable to Menu or Dialog? In both cases state would be changed by actions outside of component. That is OK to have property/attribute which reflect dynamic state.

**Comment by e111077** [comment]
I ended up writing this for dialog but was unsure of the implementation at the time. I assume the reason this was done for snackbar was because of the same reason I was unsure.

These components set `open=false` on themselves. This causes an issue with lit-html's property binding. e.g.

```ts
class MyElement extends LitElement {
  @property() isOpen = true;

  render () {
    return html`
      <mwc-dialog .open=${this.isOpen}></mwc-dialog>
    `;
  }

  show() {
    this.isOpen = true;
  }

  directShow() {
    this.shadowRoot!.querySelector('mwc-dialog')!.open = true;
  }
}
```

in the above example, if dialog closes via user interaction, then `Dialog.open === false` but `MyElement.isOpen === true`. Thus `show()` would not open the dialog because the lit lifecycle would not see a change in `isOpen` and thus not rerender. Also, if another property triggered rerender, lit-html would not update that value. On the other hand, `directShow()` would open the dialog. Though now that the [`live` directive](https://lit-html.polymer-project.org/guide/template-reference#live) exists, I believe this is much less of an issue.

Though for those not using lit-html, the `show()` and `close()` functions should still exist. 

I'm transforming this issue into a feature request and putting it on the following sprint.

**Comment by sashafirsov** [comment]
@e111077 , you could consider instead of plain @property on boolean member the attribute getter and setter.
This way it could be initializeable, actionable, and CSS selectable.  Would be a bit more verbose but easier to maintain and use. Availability from CSS is quite useful as could be used for animations, siblings control, etc. Imagine closing the dialog or snackbar accompanied by hiding shadow around source item.

**Comment by e111077** [comment]
I believe we need to figure out some standardization of attribute reflection across our components

**Comment by sashafirsov** [comment]
Agree. Just to your bucket of standard solutions.  'open' is an attribute which is popular in HTML5 ( like in `details` tag ). It also has been implemented by `mwc-menu` and `mwc-dialog`.
