### ISSUE TITLE
mwc-select: Label doesn't stay in place if value is not a string

### ISSUE THREAD

**Issue by karimayachi** [material-components/material-components-web-components#1256]
**Description**
With an mwc-select, using anything else than a string value for the mwc-select and the mwc-list-items results in the label not staying in place when focus is lost.

<img width="613" alt="image" src="https://user-images.githubusercontent.com/4971243/81053517-7ae8cc80-8ec5-11ea-8244-095b98813cd3.png">

**Reproduce**
To reproduce see this very crude JavaScript:
```javascript
import '@material/mwc-select';
import { ListItem } from '@material/mwc-list/mwc-list-item';

var select1 = document.getElementById('stringValue');
var select2 = document.getElementById('numberValue');
var select3 = document.getElementById('objectValue');

var people = [
    { name: 'John' },
    { name: 'Jane' },
    { name: 'Bob' }
]

for(var i = 0; i < people.length; i++) {
    var person = people[i];

    var item1 = new ListItem();
    item1.value = person.name;
    item1.innerText = person.name;
    select1.append(item1);

    var item2 = new ListItem();
    item2.value = i;
    item2.innerText = person.name;
    select2.append(item2);

    var item3 = new ListItem();
    item3.value = person;
    item3.innerText = person.name;
    select3.append(item3);
}

select1.value = 'John';
select2.value = 1;
select3.value = people[2];
```

**Expected behavior**
I would expect other value types to be allowed. Selecting and showing the correct item works fine with the other value types, so I guess it's intended to work with non-strings.

**Browser Version (please complete the following information):**
 - OS: MacOS 10.15.4
 - Browser: Firefox 76, Chrome 81.0

**Comment by asyncLiz** [comment]
Thanks for the issue! Similar the the native `<select>`, `<mwc-select>` only supports strings as its values. 

For numbers, this should be an easy conversion. For objects, I would recommend finding a unique key on the object (such as a database ID) that can be used as a string key to associate the object with the list item. Your application can then look up the correct object from the key with a data structure such as a Map.

Closing since this isn't a feature we intend to support.

**Comment by karimayachi** [comment]
Thank you for your reply, Liz! I only now notice that it says so in the docs... My apologies, should've checked that first... I'm using an MVVM style binding library, so I guess I can make a wrapper if I start using your library. Which I think I will, because I've been following this project for a year now and I really love what you're doing here!

I do think that a case can be made for my remark though. The original `<select>` only supported strings because it had to (HTML attribute, furthermore intended to be serialized to post data). In the wonderful world of custom element DOM properties there really is no need to impose those restrictions. Other than a semantic similarity between the two. Also: I've tested a couple of cases and it already seems to work quite well, apart from the label...

Anyway, just my two cents. 
Thanks!

**Comment by jpradelle** [comment]
I really think too that mwc-select would be awesome with numbers as key support.
I'm migrating from paper-dropdown-menu and paper-listbox, it was supporting numbers as key.
Also null value is not supported and it was on paper implementation.
Those restrictions impose to write some messy code, moreover when it's around values like `''`, `null`,  and `0`

It seems that only label is causing the issue. Which can be fixed by replacing 
```ts
const optionHasValue = this.getValue().length > 0;
```
with
```ts
const optionValue = this.getValue();
const optionHasValue = optionValue !== null && optionValue !== '';
```
in [mdc-select/foundation.ts](https://github.com/material-components/material-components-web/blob/e4180d07b51f4310425aaaea35d5fcc968f9ae4b/packages/mdc-select/foundation.ts#L213)
