### ISSUE TITLE
Allow for icon-button to be used as iconTrailing in textfield

### ISSUE THREAD

**Issue by govis** [material-components/material-components-web-components#1317]
**Describe the solution you'd like**
Looking for a way to interact with the iconTrailing and have it behave more like an icon-button than just an icon

Delete, Voice, Dropdown "icons" in the material guide would imply some level of interaction 
https://material.io/components/text-fields#filled-text-field

**Additional context**
Similar request #541, was not fully addressed

**Comment by asyncLiz** [comment]
Thanks for the issue!

This will primarily be tracked in #1215, which is investigating adding some of the missing features around helper text and icons, including interactivity.

However, this will also be possible once #760 is implemented, since it will be possible to slot your own icon button for trailing icons.

I'd recommend subscribing to both of those issues in the meantime!

Closing as a duplicate of #1215.
