### ISSUE TITLE
Add mwc-drawer to the bundle at 

### ISSUE THREAD

**Issue by MarcSkovMadsen** [material-components/material-components-web-components#1347]
I'm trying to use mwc components directly from HTML without a bundler. See https://github.com/material-components/material-components-web-components/issues/1341 for more context.

I've discovered https://glitch.com/~ribbon-weak-jaguar and it works great except that the `mwc-drawer` is missing from the imports in the `index.js` file.

I can add it manually but I think it should be there in general.

Please add. Thanks.

**Comment by asyncLiz** [comment]
Thanks for the issue!

That glitch repo is not ours, but it looks like a copy of our demos. The reason drawer and some other components like top-app-bar are not in the demo page right now is because they'd require an `<iframe>` to embed them and work properly.

We're investigating a better way to display such components with an `unfixed` attribute (see https://github.com/material-components/material-components-web-components/issues/1064).

Closing this issue in the meantime though. We do not support using MWC without a build system (even http://unpkg.com is a minimal build system). Though it's impressive if you can manage getting as build-less as possible! 

Ultimately there are too many build systems for us to take on helping maintain specific problems with each one.

**Comment by MarcSkovMadsen** [comment]
Thanks @asyncLiz . My site awesome-panel.org now runs on a bundle from the above glitch site.

Take a look. Its awesome... at least for me 😉

**Comment by MarcSkovMadsen** [comment]
And you dont have to run the app bar in iframe. You just need to set the scrol... something. 

I did that to get it working in a jupyter notebook. It works fine. See https://github.com/holoviz/panel/pull/1254
