### ISSUE TITLE
mwc-textfield min is not always a number

### ISSUE THREAD

**Issue by plumbblake** [material-components/material-components-web-components#1361]
When using the min attribute on a `mwc-textfield` it parses it as a number.  See https://github.com/material-components/material-components-web-components/blob/master/packages/textfield/src/mwc-textfield-base.ts#L304

This is not compatible with input of type `date` as you will get `nan` when setting the value to something like `min="2018-01-01"`

**Comment by asyncLiz** [comment]
This is somewhat related to #1307. While the native `<input>`'s min and max are strings to support date-time and numeric values, `<mwc-textfield>` does not officially support `type="date"`.

Our recommendation for date inputs is to use separate textfields for each of the date components (month, day, and year) until a datepicker component is implemented (#843).

I'll keep this open since we still haven't explicitly received guidance from design stating that textfields should not be used as datepickers.

**Comment by taylor-vann** [comment]
fixed with pull [1652](https://github.com/material-components/material-components-web-components/pull/1652)

**Comment by taylor-vann** [comment]
fixed with [1640](https://github.com/material-components/material-components-web-components/pull/1640)
