### ISSUE TITLE
Provide --mdc-dialog-min-height for <mwc-dialog>

### ISSUE THREAD

**Issue by ronnyroeller** [material-components/material-components-web-components#1376]
**Is your feature request related to a problem? Please describe.**
The `<mdc-dialog>` offers:
- `--mdc-dialog-min-width`
- `--mdc-dialog-max-width`
- `--mdc-dialog-max-height`

Yet, it's not possible to set the minimal height of the dialog. This looks unbalanced when setting `min-width` to a high value (e.g. 80%) for a dialog with little content.

**Describe the solution you'd like**
Add CSS custom property `--mdc-dialog-min-height`.

**Comment by asyncLiz** [comment]
Do you have any mockups or examples of your use case for a large dialog with little content? We'd like to show those to design and get feedback.

I'm cautious since this seems to be against the spirit of the Material dialog and the purpose of the min-width custom property. We also want to be cautious about adding additional custom properties, since it's difficult to remove them and we need to confirm the flexibility that they offer is aligned with spec.

Keep in mind that full-screen dialogs are a valid, albeit different use case. Are you trying to achieve something akin to a full-screen modal dialog? If so, it may be better to wait until that is implemented rather than introduce a workaround via a custom property. 

Full screen dialogs are currently being worked on in the upstream MDC library.

**Comment by ronnyroeller** [comment]
@asyncLiz Thanks a lot for your explanation. As of [spec](https://material.io/components/dialogs#full-screen-dialog), full-screen dialogs don't exist for desktop. So, we have been using large modal dialogs instead. Yet, re-reading the spec, using pages instead of large dialogs is properly the better approach.
The closest thing I could find in Google products is the contact dialog in Contacts app. This indeed has no minimal height but adjust purely based on the amount of content.
