### ISSUE TITLE
AppBar Left Align

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web-components#1452]
**Is your feature request related to a problem? Please describe.**
The actionItems allow to right align items in an app-bar, something similar for right alignment items - other than hamburger menu - would be needed for greater flexibility of use of this component.

Additionally, sometime the hamburger menu needs to be right aligned, so I think that a few improvements should be made on this specific area. Of aligning items in the app-bar.

**Describe the solution you'd like**
Adding more slots/props.

**Describe alternatives you've considered**

**Additional context**

**Comment by asyncLiz** [comment]
Thanks for the issue!

Material Design describes the anatomy of the top app bar as having the action items to the right of the navigation icon and title for left-to-right languages (https://material.io/components/app-bars-top#anatomy). The only time they and the navigation icon should be reversed would be for right-to-left languages.

This library focuses on building components that strictly adhere to the spec, and customizations should fit within the scope of that. Unfortunately this customization is not within the scope of what a Material top app bar is.

Our recommendation would be to extend, fork, or create your own Material-inspired top app bar that allows for different anatomy.

Closing since this is currently out of scope.
