### ISSUE TITLE
Pass-through attribute "global" from <mwc-radio-list-item> to its <mwc-radio>

### ISSUE THREAD

**Issue by karakonjul** [material-components/material-components-web-components#1506]
Right now attribute "global" is hardcoded when using \<mwc-radio-list-item\>:
https://github.com/material-components/material-components-web-components/blob/b6bd3308adff67d856506e15855ea17c452b6a56/packages/list/src/mwc-radio-list-item-base.ts#L53-L55

Instead, it would be better if this attribute was exposed by mwc-radio-list-item itself, like this:

`<mwc-radio ?global=${this.global}`

**Comment by dfreedm** [comment]
@e111077 Can you verify if this was intentionally set to global?

**Comment by e111077** [comment]
Hello, this was intentionally set as the radios are already in different shadow roots. If global is set to false, then they will not interact with each other.

**Comment by karakonjul** [comment]
Let me show you a more complete example where this is a problem.

`<mwc-list>`
`	<mwc-radio-list-item>one</mwc-radio-list-item>`
`	<mwc-radio-list-item>two</mwc-radio-list-item>`
`	<mwc-radio-list-item>three</mwc-radio-list-item>`
`</mwc-list>`
`<mwc-list>`
`	<mwc-radio-list-item>one</mwc-radio-list-item>`
`	<mwc-radio-list-item>two</mwc-radio-list-item>`
`	<mwc-radio-list-item>three</mwc-radio-list-item>`
`</mwc-list>`

All 6 radios in the example are sharing a group, and the only way to separate them is to use the "group" attribute of mwc-radio-list-item. This would have been fine if they were sharing a list, but being in different lists I think the default behaviour should be to separate them without the need of a group attribute. As far as I can tell, this is only achievable by exposing the currently hard-coded "global" attribute via mwc-radio-list-item, and setting it from outside depending on context.

I'll let you decide whether this issue needs to be re-opened

**Comment by e111077** [comment]
Hello, unfortunately we cannot accommodate for this solution. Even if these were mwc-radios, since they would be in the same shadow root, the two lists would still interact with each other without setting `group` on them. This is because it's not good component design for them to be self-aware of parent or sibling components.

This will require an in-depth solution, so can you please file a bug under `mwc-radio` to scope it to a particular parent. The best we can probably do is a `querySelectorAll` on a component, but that will likely not solve the issue of shadow roots or slotted components.
