### ISSUE TITLE
Refering style from one place, rather injecting it in each material component. 

### ISSUE THREAD

**Issue by ayushcsi** [material-components/material-components-web-components#1523]
HI, I am creating a frontend UI for nosql and I need to render a lot of data. I was using material design components. Due to ease of material-components-web-components, I started using it. I found issue that, in each material-components-web-components element style holds all style as attribute. With many components now rendering with style as text in component is causing high load time.

Please suggest how can I overcome this. Like using referring style from one file and not injecting it inside each element. To increase performance while rendering

**Comment by ayushcsi** [comment]
I debugged this and now understand providing local style properties in each element provides performance and customization by going through https://lit-element.polymer-project.org/guide/styles . However if there are a lot of elements the page could be heavy. I compared the same GUI created using material web components and vanilla material components and load was lot faster with vanilla components. 

I also understood how to refer from external style sheet and tested it with material design css on material web components. Is it possible to add a feature to refer from external style sheet by providing command at runtime

**Comment by asyncLiz** [comment]
Thanks for the issue!

If I understand correctly, you are concerned about having embedded styles in the same file as the custom element as opposed to having them in an external CSS stylesheet? Please correct me if I'm wrong.

The reason we are inlining CSS is to provide all of the necessary styles for the element when it loads. There are ways to try and force external stylesheets to style custom elements encapsulated by shadow dom (such as with `<link>` elements or by loading CSS and injecting it), but these methods are less performant than the bytes they save for the first page load.

Additionally, loading the elements _without_ their styles causes a Flash Of Unstyled Content (FOUC) on the page, which is something we as team avoid at all costs.

The size of the stylesheets for the elements is something we'd like to reduce and optimize, but their size will make a small impact on an application's load time. Instead, we'd encourage applications to implement features like a light app shell, code splitting, and lazy loading to improve performance and load time.

I'm going to close this issue since providing external stylesheets is out of scope for what we intend to work on with this library, but feel free to continue the discussion if you believe there are areas we can improve upon!

**Comment by ayushcsi** [comment]
Hi  asyncLiz,

Thanks for update. My main issue when I create large number of elements using material-components-web-components, there is huge load time, where as when I use vanilla material web components load time is very fast. Also when I check in memory tab of firefox the memory footprint for dom is nearly 450MB using material-components-web-components where as same with vanilla material web components it is nearly 88MB. All other memory footprint like text, function calls are also increasing 4-5 times. 

So, I just need a solution or workaround if possible that when using material-components-web-components memory footprint in browser is near of material web components, and load time is also not high.

**Comment by ayushcsi** [comment]
Hi asyncLiz,

Thanks for update. My main issue when I create large number of elements with my sample data using material-components-web-components , there is huge load time, where as when I use vanilla material web components load time is very fast. Also when I check in memory tab of firefox the memory footprint for dom is nearly 88MB using material-components-web-components where as same with vanilla material web components it is nearly 36MB. All other memory footprint like text, function calls are also increasing 3-4 times. When I use my large
![memory footprint using material-components-web-components](https://user-images.githubusercontent.com/61983787/87386138-6f004180-c5bd-11ea-9cb6-0404d70ae9e2.jpg)
![memory footprint using vanilla mdc](https://user-images.githubusercontent.com/61983787/87386145-7293c880-c5bd-11ea-9d82-95a06fd1ed5b.jpg)

 data the lag is very high

So, I just need a solution or workaround if possible that when using material-components-web-components memory footprint in browser is near of material web components, and load time is also not high.

**Comment by asyncLiz** [comment]
Can you provide links to these two sample applications so we can run benchmarks on them?

**Comment by ayushcsi** [comment]
HI asyncLiz,

Thanks for response. I am trying to get approval to share code and data set. Or will try to share bare code with mwc
