### ISSUE TITLE
Create npm package that imports all published mwc packages

### ISSUE THREAD

**Issue by jifalops** [material-components/material-components-web-components#158]
Similar to how installing and importing `material-components-web` makes all of the `MDC*` classes available.

**Comment by aomarks** [comment]
Although I agree it could be convenient, I think it's better to encourage users to only install and import the specific components you are using. This will encourage smaller NPM package sizes, smaller bundle sizes (which means faster web pages), and also means that the NPM download statistics are a little more accurate (since otherwise every download of the combined package would count as a download of all components, even when those components are not being used).
