### ISSUE TITLE
Please provide efficient MWC bundle for simple use cases

### ISSUE THREAD

**Issue by MarcSkovMadsen** [material-components/material-components-web-components#1670]
Hi Material-Components

I'm currently working on wrapping the MWC components in Python for Panel. Panel is a framework for creating awesome analytics apps in Python. Take a look at my site https://awesome-panel.org and https://mybinder.org/v2/gh/MarcSkovMadsen/awesome-panel-extensions/master?filepath=examples%2Freference%2Fframeworks%2Fmaterial%2FMaterialButton.ipynb

I found https://glitch.com/~ribbon-weak-jaguar which provided a very efficient (small, fast to load) bundle of all the mwc components that I copied and could load via

```html
<script src="https://cdn.jsdelivr.net/gh/marcskovmadsen/awesome-panel@be59521090b7c9d9ba5eb16e936034e412e2c86b/assets/js/mwc.bundled.js"></script>
```

Which made it very easy to use the mwc components without a build system.

Now https://glitch.com/~ribbon-weak-jaguar no longer exists and I can't get my bundle updated to the latest version of the mwc components. 

I don't know how to build an efficient bundle containing all the mwc components. As I am not normally a JS developer. I'm a data scientist and Python developer.

Please help. Thanks.

#### Additional Context

To me the promise of web components is that they can easily be used across frameworks and in a lot of settings. Thus I believe  you should it would help your (potential users) if you provided a bundle from a CDN.

For comparision to FAST.design by Microsoft which just launched this is natural and there from the beginning.

![image](https://user-images.githubusercontent.com/42288570/89701720-e1084400-d939-11ea-8bdb-589282d92017.png)

----

Related to https://github.com/material-components/material-components-web-components/issues/1347

**Comment by asyncLiz** [comment]
Thanks for the issue!

The topic of a CDN and bundled version of our components has been addressed a few times. I'll direct you to Elliott's great explanation of why we've chosen not to bundle our components here: https://github.com/material-components/material-components-web-components/issues/1219#issuecomment-620290605.

The CDN that FAST Components use is unpkg.com, which we've recommend several times as a non-production CDN to get started using our components, including in your previous issue https://github.com/material-components/material-components-web-components/issues/1347 and the issue comment linked above.

Closing this since unpkg.com already exists as a CDN solution, similar to FAST Components.
