### ISSUE TITLE
diff or selected event of mwc-select is undefined

### ISSUE THREAD

**Issue by gullerya** [material-components/material-components-web-components#1696]
**Describe the bug**
The `selected` event is said to have a `detail.diff` property populated with the `IndexDiff` object. This property is `undefined` for any of my attempts (going from none to some selected and switching between selected).
The only tested use-case is single select case.

**To Reproduce**
1. Create `mwc-select` element, populated with several `mwc-list-item` children
2. Set a listener on `onSelected` event like: `e => console.log(e.detail)`
3. Play with the select element, selecting one item or another
4. Observe the output in the console, all show `diff` property as `undefined`
5. Expected to see the change

**Expected behavior**
Expected to see the `diff` property of `event.detail` populated with a change.

**Browser Version (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 84

**Comment by gullerya** [comment]
Update, looking into the code of the `mwc-list-foundation` and the `mwc-list-adapter` it looks like the `diff` is provided only when working with **multi-select**.
While this explains the observed behaviour, and it ca be reduced to documentation issue, I'd say that it may be very convenient to have the previous and the new values at hand in this kind of events.

To add the last part to it - the `mwc-list` indeed behaves like said above: only a multi select flavor populates `diff`.

**Comment by asyncLiz** [comment]
Similar to list and MDC select, the intention of the `diff` is to provide a delta of multiple indices that were added and removed, not a difference between the previous and current selected index for single selection.

We'd recommending tracking the previous value of the select in your application's state to compare it to the current value as it changes.

I'll keep this issue open for mwc-select's documentation though, which needs to be updated to remove references to the `diff` since select does not support multi selection.
