### ISSUE TITLE
mwc-textfield type="datetime-local" does not show native datepicker

### ISSUE THREAD

**Issue by afberg** [material-components/material-components-web-components#1715]
**Describe the bug**
After the update to `0.18.0` `mwc-textfield` no longer renders the browser-native datepicker when set to `type="datetime-local`.

**To Reproduce**
1.  Add a component like so: `<mwc-textfield type="datetime-local"></mwc-textfield>`
2. See that no browser-native datepicker renders.

**Expected behavior**
The native datepicker should render.

**Screenshots**
**On 0.17.x:**
![image](https://user-images.githubusercontent.com/4534730/90764097-14f34a00-e2e8-11ea-8fc8-5cfd07b798e7.png)
On **0.18.x:**
![image](https://user-images.githubusercontent.com/4534730/90764179-3a805380-e2e8-11ea-9da3-c771e65cf7f0.png)

**Browser Version (please complete the following information):**
 - OS: MacOs Catalina 10.15.3 (19D76)
 - Browser: Chrome Version 84.0.4147.125 (Official Build) (64-bit)
 - Version: mwc-textfield@0.18.0

**Comment by asyncLiz** [comment]
Thanks for the bug!

This is currently working as intended, as the native icon should not be visible according to our designers due to a11y concerns. The native datepicker may still be opened by pressing spacebar, enter, or F4 while the text field is focused.

We are tracking https://bugs.chromium.org/p/chromium/issues/detail?id=939561 for a native solution that will allow us to open the datepicker from an icon click similar to a native `<input>`. I'd recommend tracking that issue for updates.
