### ISSUE TITLE
[MWC-TOP-APP-BAR | MWC-SELECT] Height/Width Issues

### ISSUE THREAD

**Issue by aress31** [material-components/material-components-web-components#1810]
**Describe the bug**
I am trying to implement a language switch - with `mwc-select - on an `mwc-top-app-bar` and the style are conflicting.

I see two issues, first the height of the topmwc-select is bigger than the one of the denser version of the top-app-bar resulting in the `mwc-select` component overflowing the `mwc-top-app-bar` and the width of the `mwc-select` being way too large and therefore taking a lot of unnecessary available space on the `mwc-top-app-bar`.

**Suggested solution**
Adding a `height` and `width` option to the `mwc-select` so that the `mwc-select` component could be used in many more ways.

**Screenshots**
![image](https://user-images.githubusercontent.com/11601622/93137957-30c6f180-f6d6-11ea-8a79-3b9360c8c2c8.png)

EDIT: Also, how could I change the `font size` of the text within my `mwc-select`, on my `top-app-bar` I defined a size of 14px for all my text element, the `mwc-select` should follow this size font in order to be harmonized.

**Comment by asyncLiz** [comment]
The height of the select may not currently be changed. This is dependent on the density system. You can subscribe to #841 for updates to that issue.

The width of the select may be changed by setting the `width` property on the select.

Font styles may be changed using the typography custom properties specified in the [global custom properties section](https://github.com/material-components/material-components-web-components/tree/master/packages/select#global-custom-properties) of the select readme.

I'm going to close this since #841 is the most appropriate issue to track the height density request.

**Comment by aress31** [comment]
Shouldn't the `mwc-select` integrate just fine with `mwc-top-app-bar` out of the box?

Also I tried to change the width like:

mwc-select {
  width: 500px;
}

Unfortunately didn't seem to work.
