### ISSUE TITLE
Enter key does not submit a form when mwc-button is present in the form

### ISSUE THREAD

**Issue by YonatanKra** [material-components/material-components-web-components#1832]
**Describe the bug**
When filling a form with and hitting enter when focused in a native text field, the form is supposed to be sent.
When mwc-button functions as the form's button, this submit does not happen.

**To Reproduce**
1. Create a simple form (with native text fields) - https://yonatankra.com/ykdemos/simple-form/
2. Fill it
3. Hit Enter while focused in a text field
4. See that it submits
5. Replace the form's button with an mw-button to the form - https://yonatankra.com/ykdemos/mfa-button/
6. Try to submit with Enter key
7. See it doesn't submit the form

**Expected behavior**
I'd expect the form to be submitted.

**Screenshots**
https://yonatankra.com/ykdemos/mfa-button/

**Browser Version (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 85.0.4183.83

**Additional context**
If adding a regular button to the form, it works again: https://yonatankra.com/ykdemos/mwc-button-with-native-button/

**Comment by asyncLiz** [comment]
Thanks for the bug! This is a known issue since custom elements do not integrate with native forms. We're tracking form integration in https://github.com/material-components/material-components-web-components/issues/289, I'd recommend following that issue for updates!

In the meantime, the appropriate workaround is to add an event listener and submit the form manually.
