### ISSUE TITLE
Unable to set min-width of <mwc-button>

### ISSUE THREAD

**Issue by Glamurio** [material-components/material-components-web-components#1982]
All buttons currently have a min-width of 64 pixels.

This is what it looks like:
![image](https://user-images.githubusercontent.com/51779813/100482979-836e5200-30f8-11eb-8047-9e1564ffbd6e.png)

This is what it should look like:
![image](https://user-images.githubusercontent.com/51779813/100483276-9e40c680-30f8-11eb-8dc1-271dee646bc6.png)

I've already tried to mitigate this with `--mdc-button-horizontal-padding: 0;` but to no avail.

If there was a new root variable such as `--mdc-button-width` or `--mdc-button-min-width` I'd appreciate it very much.

**Comment by e111077** [comment]
Hello, this is unfortunately intentional as min-width is meant to be 64px. This button is intended to be used with text and not simply icons. Our internal design guidelines for searchboxes instead use [icon-buttons](https://github.com/material-components/material-components-web-components/tree/master/packages/icon-button) inside the searchbox itself.

e.g. https://jsbin.com/dodokazeki/1/edit?html,output
