### ISSUE TITLE
"mwc-ripple" has already been used with this registry error on v0.20.0

### ISSUE THREAD

**Issue by ais-one** [material-components/material-components-web-components#1999]
I get the following error when running

DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-ripple" has already been used with this registry

All I did was to upgrade from 0.19.1 to 0.20.0

I used the following mwc components below

    "@material/mwc-button": "^0.20.0",
    "@material/mwc-dialog": "^0.20.0",
    "@material/mwc-drawer": "^0.20.0",
    "@material/mwc-icon": "^0.20.0",
    "@material/mwc-icon-button": "^0.20.0",
    "@material/mwc-list": "^0.20.0",
    "@material/mwc-menu": "^0.20.0",
    "@material/mwc-select": "^0.20.0",
    "@material/mwc-textfield": "^0.20.0",
    "@material/mwc-top-app-bar-fixed": "^0.20.0",

**Comment by govis** [comment]
Same here, but with <code>mwc-list-item</code>
<pre><code>decorators.js:15 Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-list-item" has already been used with this registry
    at legacyCustomElement (http://localhost:60001/node_modules/lit-element/lib/decorators.js:15:27)
    at http://localhost:60001/node_modules/lit-element/lib/decorators.js:50:5
    at __decorate (http://localhost:60001/node_modules/tslib/tslib.es6.js:56:95)
    at http://localhost:60001/node_modules/@material/mwc-list/mwc-list-item:24:12</code></pre>

**Comment by taylor-vann** [comment]
Hey @ais-one!

Sorry to hear about the difficulties. Usually this happens when conflicting versions of a component.

Would you mind sharing your configuration so we could try to help you a little better?

But yah until then, I'd double check to make sure there is only 1 mwc-ripple (or mwc-list-item) in your build

**Comment by ais-one** [comment]
Hi,

I have code in github, it is part of a dev cookbook on how to use things

you can see the issue using the steps below

git clone https://github.com/ais-one/vue-crud-x.git
git checkout develop
cd vue-crud-x/example-vite
npm i
npm run dev
navigate to http://127.0.0.1:8080

you will see the warning in the console logs (it is actually an error, I
added some scripts to treat error as warning in index.html, so if you
remove it, you will see the errors


actually I built a component called mwc-multiselect (using mwc-textfield
and mwc-select) , it is also broken in 0.20.1 but that is for me to fix.


The information herein is given on a general basis without obligation and
is strictly for information purposes only. We do not warrant the accuracy
or completeness of the information, graphics, links, or other items
contained herein, and expressly disclaim liability for errors or omissions
in these materials.

**Comment by contis2908** [comment]
I am receiving the same error `DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-icon" has already been used with this registry` for the mwc-icon after I have imported the mwc-button.
Seems as if this import is breaking it due to a different version?

**Comment by asyncLiz** [comment]
Thanks for the issue!

This appears to be a problem with Vite's `optimizeDeps` option. After running your project's build, I noticed that it was pre-bundling some, but not all, MWC elements into modules. MWC elements share dependencies, such as `<mwc-ripple>`. The problem occurs when `<mwc-list>` is bundled into `/@modules/mwc-list/mwc-list.js` and has its own bundled copy of `<mwc-ripple>`, along with `/@modules/mwc-button/mwc-button.js` and others.

If following this pattern, every single MWC element should be compiled to its own module and not bundled (they share a lot of heavy code, such as LitElement and lit-html itself, which should not be included multiple times in a page: it can lead to very odd bugs).

I would caution against doing this pattern and instead bundle all MWC dependencies into a single module that is imported if your project wished to use ES imports. For production usage, our recommendation is still to bundle all code and code split where appropriate for lazy loading.

Closing since this is a Vite-specific issue.

**Comment by ais-one** [comment]
Hi @asyncLiz 

Thank you for looking at it.

Could I trouble you for just one check... I had removed mwc-* from vite optimizeDeps, is it still bundling the way you described which generated the issue?

Then I have more detail to raise it to the vite developers.

**Comment by ais-one** [comment]
Hi,

I managed to resolve it and you can find out in this link at vite site...

https://github.com/vitejs/vite/issues/1235#issuecomment-745072967
