### ISSUE TITLE
[mwc-icon-button] display label as hint (tool tip)

### ISSUE THREAD

**Issue by masaoliou** [material-components/material-components-web-components#2004]
Imagine many `mwc-icon-button` are placed on `mwc-top-app-bar`.

It is desirable for users to see the `label` value of 'mwc-icon-button' as hint or tool tip when they hover their mouses over each of these elements just as legacy polymer `paper-icon-button` does.

**Comment by taylor-vann** [comment]
Hey @masaoliou !
Thanks for this suggestion, I think that's a good suggestion. I will talk to the team!

**Comment by taylor-vann** [comment]
Hey @masaoliou

After conferring with the team, we have a screen reader accessible tooltip in the pipeline (feel free to track our progress with #1499). Currently we don't recommend the feature you're trying to implement. But, again, we have a tooltip in development.

You can provide a "title" attribute to any of our elements and the browser will render the text, however it has accessibility issues which is why we recommend waiting for our official tooltip.

Thanks
