### ISSUE TITLE
How to style shadow root elements in mwc-formfields?

### ISSUE THREAD

**Issue by rutwick-alic** [material-components/material-components-web-components#2013]
I want to add style to the label text that **mwc-formfield** adds with a checkbox. Add an icon after the text to be precise, so I am trying to use :after and content to do so. But my CSS is not applied since it is rendered inside shadow dom. Anyway to do it? Ionic exposes shadow parts for styling, do we have something like that?

**Comment by asyncLiz** [comment]
Thanks for the issue!

This sort of style change (adding additional arbitrary HTML, such as an icon) is not recommended or supported by Material for formfield. Formfield is already used with iconography (checkboxes, radio icons, and switches). Adding additional icons would draw attention away from the label's main interactive icon, which is why it's not recommended and protected by the shadow root.

Due to that, we won't be adding support into `<mwc-formfield>` for this feature, but you are welcome to extend the element or create your own that satisfies your UI requirements!
