### ISSUE TITLE
Enter in form always closes mwc-dialog, despite workarounds

### ISSUE THREAD

**Issue by bennypowers** [material-components/material-components-web-components#2052]
**Describe the bug**
Sometimes users want to prevent `<mwc-dialog>` from firing primary action on Enter keypresses. 

For example, if the form contains a, dropdown, if the user selects a dropdown item with enter, it closes the dialog instead of only closing the dropdown

Workaround attempts:
1. slot the action buttons, but use `event.preventDefault()` - dialog still closes
2. don't slot the action buttons - empty hard-coded 54px high footer
3. slot the cancel button but not the action button, and use stacked - buttons not aligned
Conclusion: there's no way to use mwc-dialog 0.20 with selects, dropdowns, or other components for which Enter key is a legitimate but non-closing user action

the dialog content's padding is hard coded, so my only recourse is to use css transforms to move the non-slotted button, and I'll still get excess whitespace

The one partial workaround I found was to disable the primary action button when the form is invalid
But this only works if all the form fields are required

Case:
form has three fields,
1. text, required
2. select, required
3. select, optional
A. user types text, then hits Enter
  => Dialog does not close
B. user hits Tab, Space, DownArrow, DownArrow, Enter
  => dialog closes, but user could not select from the second select field

**To Reproduce**
1. Add a dropdown-like component to a dialog's body
2. open the dialog
3. open the dropdown
4. focus an item with arrow keys
5. select the item with Enter key

**Expected behavior**
Dropdown closes, but dialog remains open

**Comment by nicolasr75** [comment]
I have the described problem with mwc-textarea's.

I think this issue is related https://github.com/material-components/material-components-web-components/issues/629

If I interpret the closing comment by @e111077 correctly, there will be no change to this behavior.

**Comment by asyncLiz** [comment]
This should be possible now with the [`get/setSuppressDefaultPressSelector()` MDC foundation methods](https://github.com/material-components/material-components-web/blob/1433cceeca7b5f075425013939c1894a5f9243e7/packages/mdc-dialog/foundation.ts#L171-L177) that were added a while back. We should be able to expose these via a property on the web component for custom use cases where the default press (enter) needs to be suppressed for specific needs.

Additionally, we can update the default selector to be more compatible with MWC elements so that `<mwc-textarea>` and menu-based `<mwc-list-item>` do not trigger the default press.

**Comment by e111077** [comment]
I'll take this up now

**Comment by asyncLiz** [comment]
Fixed in https://github.com/material-components/material-components-web-components/pull/2073
