### ISSUE TITLE
mwc-select options cannot be scrolled into view if inside overflow:hidden

### ISSUE THREAD

**Issue by yujiri8** [material-components/material-components-web-components#2062]
### Describe the bug

mwc-select options are curtailed by overflow:hidden, unlike native \<select\> options, with no apparent recourse to select them.

### To Reproduce
1. Have markup like:
```html
<div style="height:70%; background-color:orange">will cover your options</div>
<div style="overflow:hidden">
  <mwc-select label="thingies">
    <!-- put a few mwc-list-items -->
  </mwc-select>
</div>
```
2. Open the menu.

### Expected behavior
It allows options to be displayed anyway, overriding `overflow: hidden` if necessary. This is what native \<select\> does.

### Actual behavior
The options extend upward (because it's more than halfway down the screen), are covered by the orange div, and cannot be scrolled into view. Safari seems to think the options are in view because they would be if not for the `overflow:hidden`, and so it won't let you scroll any farther, making it impossible to select the items.

### Browser Version:
 - OS: iOS
 - Browser: Safari
 - Version: 14.2

**Comment by asyncLiz** [comment]
Thanks for the bug!

Our recommendation for MDC (https://github.com/material-components/material-components-web/issues/5590) is to set select's menu to fixed and provide an explicit width for both the anchor and menu. We can update `<mwc-select>` to expose this capability for MWC as well.

**Comment by DannyMoerkerke** [comment]
Could you please explain what I should add to mwc-select to get this working?
This is quite vague and I have no idea what to do here, thanks!

**Comment by asyncLiz** [comment]
Have you tried using the [`fixedMenuPosition` attribute documented in the select's readme](https://github.com/material-components/material-components-web-components/tree/master/packages/select#propertiesattributes)?

```
<div style="overflow: hidden">
  <div>
    <mwc-select fixedMenuPosition>
        ...
    </mwc-select>
  </div>
</div>
```
Demo: https://jsbin.com/pavileceya/edit?html,output

Keep in mind two things:

1. We recommend setting a fixed width for both the select and the menu (using `width`, `--mdc-menu-min-width`, and `--mdc-menu-max-width` on the `<mwc-select>` element)
2. We don't recommend scrolling while the menu is open, since the menu will remain fixed but the text field element will not. This property is intended for overflow elements such as dialog, which do not scroll the entire page. For the purpose of the demo, I've included page scrolling so you can see what this looks like.

**Comment by DannyMoerkerke** [comment]
Thanks for your quick response.
Your demo works but unfortunately it still doesn't work for me.

I use the components as npm dependencies and have updated all to 0.21.0-canary.fe73953b.0 but unfortunately that still doesn't work.
Could it have to do with the version I use?
