### ISSUE TITLE
mwc-slider layout in mwc-dialog not updated properly.

### ISSUE THREAD

**Issue by vdegenne** [material-components/material-components-web-components#2117]
An example is better than words, so here's what I'm facing : 

Click on the upper right corner gear icon and see how the slider renders.
https://vdegenne.github.io/htmlpreview/?https://github.com/vdegenne/hanja-training/blob/slider-glitch/index.html
(branch `slider-glitch`)

The pin is not properly placed on the current value. I believe this is because the dialog was not open yet so the pin places itself on the location relative to the directive `width: 100%` which is smaller than when it renders.
I am aware of the `layout` function on the slider element to readjust but even if it's called beforehand it has no effect for the same reason mentioned above.
I wanted to report this behavior because even it's not really a bug, I think it's a discrepancy of how one would expect it to work like.

And here is the nasty fix I found, not the best one I believe but it's just to show you what I was expecting:
https://github.com/vdegenne/hanja-training/blob/ecbe8b81e08f79f671db14abe3da0353575b85df/app.ts#L104-L108
(branch `slider-fix`)

I am using version `0.20.0` for all the elements.

**Comment by e111077** [comment]
Hello, this is expected behavior and you are correctly calling layout and your reasoning for the issue is also correct, but I'd suggest to wait for dialog's `opened` event to call the function rather than setting a timeout.

example: https://jsbin.com/kugaveroda/edit?html,output

Additionally, we are currently in the process of rewriting slider to the Material 2 version. Unfortunately we decided not to call layout on resize because we found the impact of calling it often to be too expensive as well as having to add any ResizeObserver polyfills. We may consider this later if we ever drop IE support and if Typescript ever adds ResizeObserver support as it is currently a hassle to implement the types without breaking users
