### ISSUE TITLE
mwc-ripple: Ripple is not working since "0.14.0" version. 

### ISSUE THREAD

**Issue by nirmalbaldaniya-dream** [material-components/material-components-web-components#2139]
I have tried to use "mwc-ripple" in simple `html` page for simplicity. It does not throw any error but ripple effect is not being shown.

Note: It's working properly in "0.13.0" version. From "0.14.0" it's not working.

**index.html**
```
<html>
  <head>
    <meta charset="UTF-8" />
    <style>
      .container {
        width: 100px;
        height: 100px;
        position: relative;
        border: 1px solid red;
      }
    </style>
  </head>
  <body>
    <noscript>
      Please enable JavaScript to view this website.
    </noscript>

    <!-- Load webcomponents-loader.js to check and load any polyfills your browser needs -->
    <script src="/node_modules/@webcomponents/webcomponentsjs/webcomponents-loader.js"></script>
    <script
      src="/node_modules/@material/mwc-ripple/mwc-ripple.js"
      type="module"
    ></script>
    <div class="container" tabindex="0">
      <mwc-ripple></mwc-ripple>
    </div>
  </body>
</html>
```
**package.json**
```
{
  "name": "@dreamworld/dw-ripple",
  "version": "0.0.0-development",
  "description": "Ripple element",
  "main": "dw-ripple.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/DreamworldSolutions/dw-ripple.git"
  },
  "author": "Nirmal",
  "dependencies": {
    "@material/mwc-ripple": "^0.20.0",
    "@webcomponents/webcomponentsjs": "^2.2.10"
  }
}
```

It's usage pattern is as per https://www.npmjs.com/package/@material/mwc-ripple guideline.
If it's usage pattern is changed, please let me know.

**Expected behavior**
Ripple effect should be shown.

**Browser Version **
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [88.0.4324.104]

**Comment by taylor-vann** [comment]
hey @nirmalbaldaniya-dream !

Thanks for submitting.

There's some [javascript](https://github.com/material-components/material-components-web-components/blob/master/demos/ripple/index.js) needed to implement `mwc-ripple`. Here is the [javascript](https://github.com/material-components/material-components-web-components/blob/master/demos/ripple/index.js) found in our [demo](https://material-components.github.io/material-components-web-components/demos/ripple/).

Mainly, `mwc-ripple` needs help identifying the parent element to ripple across.

Definitely check out the [javascript](https://github.com/material-components/material-components-web-components/blob/master/demos/ripple/index.js) to see how you can more fully implement `mwc-ripple`.

Best of luck!

I will be closing this issue because it's not exactly a bug. It's more to do with implementation.

**Comment by nirmalbaldaniya-dream** [comment]
@taylor-vann , Thank you very much..
