### ISSUE TITLE
Add layoutOptions to mwc-select to update selectedText from list item

### ISSUE THREAD

**Issue by kaifaty** [material-components/material-components-web-components#2183]
selectedText keep store old value of selected mwc-list-item.
I find the way temporarily fix the problem: 
create get/set accessors
```
set balance(value: Balance | null){
        const oldValue = this._balance;
        this._balance = value;
        this.requestUpdate('balance', oldValue);
        
        if(this.mdcSelect){
            //@ts-ignore
            const adapter = this.mdcSelect.createAdapter();
            setTimeout(() => {
                adapter.setSelectedText(this.mdcSelect.selected.innerText);
            })
        }
    }

// element
<mwc-select required .value = "${this.token}">
    ${this.tokens.map(c => 
            html`<mwc-list-item value = "${c.symbol}">${c.symbol}${
                this.balance ? html` - ${this.balance.getFormatedVol(c.symbol, 'mainnet')}`
                : nothing
            }</mwc-list-item>`)
    }                                    
</mwc-select>

```

**Comment by asyncLiz** [comment]
Thanks for the issue!

Select is not updating because the list items themselves are not changing, just their text. Select does not know that the item itself changed. This can be fixed by actually rendering a different `<mwc-list-item>` instead of updating the existing one.

With lit-html, you can accomplish this with the [repeat directive](https://lit-html.polymer-project.org/guide/template-reference#repeat) instead of mapping an array (which re-uses the rendered elements based on their index). With `repeat()`, provide a unique identifier for each list item. Whatever you're using for the value attribute is likely a good candidate.

```ts
repeat(this.tokens, c => c.symbol, c => html`...`);
```

Here is a demo of `<mwc-select>` and swapping item sets. https://stackblitz.com/edit/typescript-dm4kj7?file=index.ts

Note that if you select an item that is not present in the next set (anything other than "Option One"), the selected text will be cleared. However, if "Option One" is selected, it will remain selected as sets are swapped, even though it's in a different index position.

Hope that helps! Let us know if you have any other questions.

**Comment by kaifaty** [comment]
> 
> 
> Thanks for the issue!
> 
> Select is not updating because the list items themselves are not changing, just their text. Select does not know that the item itself changed. This can be fixed by actually rendering a different `<mwc-list-item>` instead of updating the existing one.
> 
> With lit-html, you can accomplish this with the [repeat directive](https://lit-html.polymer-project.org/guide/template-reference#repeat) instead of mapping an array (which re-uses the rendered elements based on their index). With `repeat()`, provide a unique identifier for each list item. Whatever you're using for the value attribute is likely a good candidate.
> 
> ```ts
> repeat(this.tokens, c => c.symbol, c => html`...`);
> ```
> 
> Here is a demo of `<mwc-select>` and swapping item sets. https://stackblitz.com/edit/typescript-dm4kj7?file=index.ts
> 
> Note that if you select an item that is not present in the next set (anything other than "Option One"), the selected text will be cleared. However, if "Option One" is selected, it will remain selected as sets are swapped, even though it's in a different index position.
> 
> Hope that helps! Let us know if you have any other questions.

This is not help. Check this demo: 
https://stackblitz.com/edit/typescript-aamqs3?file=index.ts
The issue is after "Update options" button pressed content of selected text must change.

**Comment by asyncLiz** [comment]
Thanks for updating the demo! The suggested fix is still possible, you just need to update the key for the list item (since it's changing) so that the select knows it's no longer the same list item.

In the provided demo, we're using the `value` property as the key, but you can use anything for the key as long as it's unique per item. If the text of the item changes, that should be a good indication that technically it's a different item.

https://stackblitz.com/edit/typescript-ac4vd9?file=index.ts

If this still does not work for you, I'm assuming the reason is because you don't want to update the text without changing the value of the list item itself.

If so, can you describe the use case you have where the displayed text of the list item needs to change without being a different list item? How does the user know the option is the same value if the text is different?

**Comment by kaifaty** [comment]
> If this still does not work for you, I'm assuming the reason is because you don't want to update the text without changing the value of the list item itself.
> 
> If so, can you describe the use case you have where the displayed text of the list item needs to change without being a different list item? How does the user know the option is the same value if the text is different?

In my case user select a currency which he spend for buy another currency. When wallet is connected in that select also shows balance of that currency. 
![изображение](https://user-images.githubusercontent.com/11953142/108669782-83b39900-74ff-11eb-89dc-e7802c2d9a70.png)
![изображение](https://user-images.githubusercontent.com/11953142/108669840-9f1ea400-74ff-11eb-8916-a1aeedd4a58e.png)

**Comment by asyncLiz** [comment]
Thanks for the clarification!

Can you try the following when you update your options to see if this fixes your issue?

```js
async updateOptions() {
  this.tokens = updated; // wallet connected, logic to update tokens property
  await this.updateComplete; // wait for the next LitElement render...
  this.mdcSelect.mdcFoundation.layoutOptions(); // ...then inform select that the options changed.
}
```

**Comment by kaifaty** [comment]
> 
> 
> Thanks for the clarification!
> 
> Can you try the following when you update your options to see if this fixes your issue?
> 
> ```js
> async updateOptions() {
>   this.tokens = updated; // wallet connected, logic to update tokens property
>   await this.updateComplete; // wait for the next LitElement render...
>   this.mdcSelect.mdcFoundation.layoutOptions(); // ...then inform select that the options changed.
> }
> ```

Yes, that's fix the problem, but mdcFoundation property is protected.

**Comment by asyncLiz** [comment]
Great! I'll reopen this issue to add a `layoutOptions()` function on `<mwc-select>` to support this use case.
