### ISSUE TITLE
Expose progress of linear-progress as css variable

### ISSUE THREAD

**Issue by yinonov** [material-components/material-components-web-components#2218]
**Is your feature request related to a problem? Please describe.**
linear progress cannot be custom-shaped properly (border-radius) due to its _.mdc-linear-progress__bar-inner_ being (transform) scaled
![image](https://user-images.githubusercontent.com/15140652/109993030-8ccd1300-7d14-11eb-9683-edad87a6425a.png)
causing the _.mdc-linear-progress__bar-inner_ element to have different border radius than the actual defined value (_10px_)

**Describe the solution you'd like**
expose the ***progress*** value as css variable so it's possible to calculate radius according to its scaled value
```
border-radius: calc(var(--radius) / var(--mdc-linear-progress)) / var(--radius);
transform: scaleX(var(--mdc-linear-progress))
```
**Describe alternatives you've considered**
expose a ***shape*** property/attribute in the linear-progress API and set the calculated value from within the linear progress component itself

**Additional context**
see more on [changing scale and border-radius](https://css-tricks.com/various-methods-for-expanding-a-box-while-preserving-the-border-radius/#changing-scale)

**Comment by yinonov** [comment]
mdc's indeterminate scale animation should probably update such variable as well
###### @material/linear-progress/_keyframes.scss
```js
@mixin primary-indeterminate-scale-keyframes_ {
  @keyframes mdc-linear-progress-primary-indeterminate-scale {
    0% {
      transform: scaleX(0.08);
    }

    36.65% {
      animation-timing-function: cubic-bezier(0.334731, 0.12482, 0.785844, 1);
      transform: scaleX(0.08);
    }

    69.15% {
      animation-timing-function: cubic-bezier(0.06, 0.11, 0.6, 1);
      transform: scaleX(0.661479);
    }

    100% {
      transform: scaleX(0.08);
    }
  }
}
```

**Comment by taylor-vann** [comment]
Hey @yinonov !

Thanks for the suggested feature. Unfortunately, exposing the 'progress' of the linear progress bar via a CSS Custom Property is not going to be supported

The TLDR explanation is the value of a CSS Custom Property could override the local state of the linear-progress element. That's not ideal.

We provide a chance to update progress via the [progress attribute](https://github.com/material-components/material-components-web-components/tree/master/packages/linear-progress#propertiesattributes). I believe that will have the same effect as your CSS custom property suggestion. This keeps the progress contained within an instance of linear-progress.

In your suggestion, you would have to make a custom property for every linear progress in the document. Otherwise a single CSS Custom Property could potentially override every linear progress in the entire document to a single value.

Although the feature is a unique one, it's not exactly supported behavior and potentially creates a lot of side effects.

**Comment by taylor-vann** [comment]
Hey @yinonov !

Thanks for the suggested feature. Unfortunately, exposing the 'progress' of the linear progress bar via a CSS Custom Property is not going to be supported

The TLDR explanation is the value of a CSS Custom Property could override the local state of the linear-progress element. That's not ideal.

We provide a chance to update progress via the progress attribute. I believe that will have the same effect as your CSS custom property suggestion. This keeps the progress contained within an instance of linear-progress.

In your suggestion, you would have to make a custom property for every linear progress in the document. Otherwise a single CSS Custom Property could potentially override every linear progress in the entire document to a single value.

Although the feature is a unique one, it's not exactly supported behavior and potentially creates a lot of side effects.

**Comment by yinonov** [comment]
Thanks for the detailed answer.
just to clarify, the focus I proposed is unidirectional internal reflection of progress as css variable, so that it will be possible to use in the css scope.

Thanks for putting the time
