### ISSUE TITLE
When zoomed, text fields have an extra bottom border 

### ISSUE THREAD

**Issue by aarondrabeck** [material-components/material-components-web-components#2275]
**Describe the bug**
![image](https://user-images.githubusercontent.com/9825025/112352416-5be75a80-8c90-11eb-9443-da45a26d6ba1.png)

As you can see, the erroneous underline seems to only be the width of the label. 

This only seems to occur if zoomed in Chrome.  I have not checked if it occurs if you have Windows scaling on.  

Our team has noticed this bug for ages so it wasn't recently introduced. 

Thanks!

**To Reproduce**
Zoom the page with an outline mwc-textfield

**Browser Version (please complete the following information):**
All

**Comment by asyncLiz** [comment]
Unfortunately this is a Chrome rendering bug with `rgba()` colors that occurs because the border section does not have a radius while the sections next to it does. I've [filed a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1195929) to track a fix.

In the meantime, you can set [`--mdc-text-field-outlined-idle-border-color` and other custom properties](https://github.com/material-components/material-components-web-components/tree/master/packages/textfield#css-custom-properties) to flat colors to resolve the issue in Chrome if it's a blocker.
