### ISSUE TITLE
Browser's back button without closing modal mwc-dialog makes controls in previous page non-responsive

### ISSUE THREAD

**Issue by hnurtj** [material-components/material-components-web-components#2318]
**Describe the bug**
Going back to previous page using browser's back button without closing modal mwc-dialog makes all controls inaccessible (not responsive to users).
I'm not sure if this is a bug or is there something missing from the way I use it?

**To Reproduce**
Repo for sample web app: [https://github.com/hnurtj/test-dialog1](https://github.com/hnurtj/test-dialog1)
1. The first link will activate the element which has a button to open up a modal dialog.
2. Press open dialog button to open up the modal dialog.
3. Press browser's back button wthout closing the dialog.

At this state, the controls (links and button) on the previous page doesn't respond to users (cannot be clicked).
When the web app is made into installable PWA, users who accidentally press the smartphone back button with a modal dialog opened will find the app unusable.

**Expected behavior**
Everything (all controls on the previous page) should still be accessible and responds to users.

**Browser Version (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 89

**Comment by dfreedm** [comment]
Hi, would you mind making a live demo of this issue on Glitch? That would help us debug this more quickly.

**Comment by hnurtj** [comment]
@dfreedm  Not at all, 
Here's the [project](https://glitch.com/edit/#!/sphenoid-spiffy-quiet), and the [live site](https://sphenoid-spiffy-quiet.glitch.me)

**Comment by dfreedm** [comment]
Thanks! This interaction might only occur because you have a router, but I think there is some cleanup code in [`Drawer disconnectedCallback`](https://github.com/material-components/material-components-web-components/blob/master/packages/dialog/mwc-dialog-base.ts#L368) that isn't removing the focus trap.

**Comment by e111077** [comment]
woah this is a gnarly one!

**Comment by e111077** [comment]
This is due to you setting `display:none` on the element without it removing the component. Unfortunately, there's not much we can do on our end here as the element is not actually removed from the page. I'd recommend if your router does not disconnect the element from the page, that it have a cleanup function before / after page change that either closes the dialog or disconnects it from the DOM
