### ISSUE TITLE
[mwc-select] auto select upon options updated (native select parity)

### ISSUE THREAD

**Issue by gullerya** [material-components/material-components-web-components#2342]
**Describe the bug**
When setting the options of the `mwc-select` component, say post render, asyncly, the value of the select component is not being changed.
Native select behaves differently - when the options 'injected', the first option is automatically become selected [CodePen here](https://codepen.io/gullerya/pen/GRrYjoy).

**To Reproduce**
1. Insert into the DOM `<mwc-select></mwc-select>`
2. Wait a bit, to let the init cycle to settle down
3. Do `<selectElementReference>.innerHTML = '<mwc-list-item value="1">1</mwc-list-item><mwc-list-item value="2">2</mwc-list-item>'`
4. Observe that preselect of the first item is NOT happening

**Expected behavior**
When the options list is replaced:
- if the current value of the list is not in options anymore - do select the first option (and notify on change)
- if the current value of the list is in the options - ensure that the option's label is updated as per relevant option in the list

Update: there are 2 misbehaves that I'm seeing happening due to this issue:
- when the options are set to a whole new list of values, the value (and as such the visibly chosen option's text) remains the old one
- when the options are set to a new list of values when some of the values are overlapping (and say that the currently selected value __is present__ in the new list, but with __different label__) - the label remains the old one

**Comment by e111077** [comment]
Heya, here you need to call the `layoutOptions` method. It was only in canary, but just released in `v0.21.0`

**Comment by gullerya** [comment]
What do you mean "you need to call" - is it something that consumer need to do upon options update or the `mwc-select` itself watches for slotted/assigned items change and does it?
Please pay attention, that consumer driven approach is not quite convenient, since mostly options are 'injected' via some data-centric framework like Vue/Angular and there is no actual code scripted to perform some kind of a 'post-inject-layout' call.

**Comment by e111077** [comment]
Hello, sorry for the lack of clarity:

When the options inside the select change it is necessary to call [`mwcSelect.layoutOptions()`](https://github.com/material-components/material-components-web-components/tree/master/packages/select#methods).

I understand the DX issues associated with this, and as of now we cannot watch slot changes due to current limitations with google internal tooling. We are actively considering other options.

In the meantime it's possible to set a mutation observer on the select. [Demo](https://lit.dev/playground/#project=W3sibmFtZSI6InNpbXBsZS1ncmVldGluZy50cyIsImNvbnRlbnQiOiJpbXBvcnQge2h0bWwsIGNzcywgTGl0RWxlbWVudCwgY3VzdG9tRWxlbWVudCwgc3RhdGUsIHF1ZXJ5fSBmcm9tICdsaXQtZWxlbWVudCc7XG5pbXBvcnQgJ0BtYXRlcmlhbC9td2Mtc2VsZWN0JztcbmltcG9ydCB7U2VsZWN0fSBmcm9tICdAbWF0ZXJpYWwvbXdjLXNlbGVjdCc7XG5cbkBjdXN0b21FbGVtZW50KCdzaW1wbGUtZ3JlZXRpbmcnKVxuZXhwb3J0IGNsYXNzIFNpbXBsZUdyZWV0aW5nIGV4dGVuZHMgTGl0RWxlbWVudCB7XG4gIHN0YXRpYyBzdHlsZXMgPSBjc3NgcCB7IGNvbG9yOiBibHVlIH1gO1xuXG4gIEBzdGF0ZSgpIGNoaWxkVG9nZ2xlID0gZmFsc2U7XG4gIEBxdWVyeSgnbXdjLXNlbGVjdCcpIHNlbGVjdEVsITogU2VsZWN0O1xuICBcbiAgcHJpdmF0ZSBtdXRhdGlvbk9ic2VydmVyOiBNdXRhdGlvbk9ic2VydmVyfG51bGwgPSBudWxsO1xuXG4gIHJlbmRlcigpIHtcbiAgICByZXR1cm4gaHRtbGBcbiAgICAgIDxtd2Mtc2VsZWN0IG91dGxpbmVkPlxuICAgICAgICAkeyF0aGlzLmNoaWxkVG9nZ2xlID8gaHRtbGBcbiAgICAgICAgICA8bXdjLWxpc3QtaXRlbSB2YWx1ZT1cIjFcIiBzZWxlY3RlZD4xPC9td2MtbGlzdC1pdGVtPlxuICAgICAgICAgIDxtd2MtbGlzdC1pdGVtIHZhbHVlPVwiMlwiPjI8L213Yy1saXN0LWl0ZW0-XG4gICAgICAgIGAgOiBodG1sYFxuICAgICAgICAgIDxtd2MtbGlzdC1pdGVtIHZhbHVlPVwiM1wiIHNlbGVjdGVkPjM8L213Yy1saXN0LWl0ZW0-XG4gICAgICAgICAgPG13Yy1saXN0LWl0ZW0gdmFsdWU9XCI0XCI-NDwvbXdjLWxpc3QtaXRlbT5cbiAgICAgICAgYH1cbiAgICAgIDwvbXdjLXNlbGVjdD5cbiAgICAgIDxidXR0b24gQGNsaWNrPSR7KCkgPT4gKHRoaXMuY2hpbGRUb2dnbGUgPSAhdGhpcy5jaGlsZFRvZ2dsZSl9PmNsaWNrIHRvIGFkZCBjaGlsZHJlbjwvYnV0dG9uPlxuICAgIGA7XG4gIH1cbiAgXG4gIGZpcnN0VXBkYXRlZCgpIHtcbiAgICB0aGlzLm11dGF0aW9uT2JzZXJ2ZXIgPSBuZXcgTXV0YXRpb25PYnNlcnZlcih0aGlzLm9uTXV0YXRpb24uYmluZCh0aGlzKSk7XG4gICAgdGhpcy5tdXRhdGlvbk9ic2VydmVyLm9ic2VydmUodGhpcy5zZWxlY3RFbCwge2NoaWxkTGlzdDogdHJ1ZX0pO1xuICB9XG4gIFxuICBkaXNjb25uZWN0ZWRDYWxsYmFjaygpIHtcbiAgICBzdXBlci5kaXNjb25uZWN0ZWRDYWxsYmFjaygpO1xuICAgIHRoaXMubXV0YXRpb25PYnNlcnZlci5kaXNjb25uZWN0KCk7XG4gIH1cbiAgXG4gIHByaXZhdGUgYXN5bmMgb25NdXRhdGlvbihtdXRhdGlvbnM6IE11dGF0aW9uUmVjb3JkW10pIHtcbiAgICBmb3IgKGNvbnN0IG11dGF0aW9uIG9mIG11dGF0aW9ucykge1xuICAgICAgaWYgKG11dGF0aW9uLnR5cGUgIT09ICdjaGlsZExpc3QnKSB7XG4gICAgICAgIGNvbnRpbnVlO1xuICAgICAgfVxuXG4gICAgICBhd2FpdCB0aGlzLnVwZGF0ZUNvbXBsZXRlO1xuICAgICAgdGhpcy5zZWxlY3RFbC5sYXlvdXRPcHRpb25zKCk7XG4gICAgICBicmVhaztcbiAgICB9XG4gIH1cbn1cbiJ9LHsibmFtZSI6ImluZGV4Lmh0bWwiLCJjb250ZW50IjoiPCFET0NUWVBFIGh0bWw-XG48aGVhZD5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwiLi9zaW1wbGUtZ3JlZXRpbmcuanNcIj48L3NjcmlwdD5cbjwvaGVhZD5cbjxib2R5PlxuICA8c2ltcGxlLWdyZWV0aW5nIG5hbWU9XCJXb3JsZFwiPjwvc2ltcGxlLWdyZWV0aW5nPlxuPC9ib2R5PlxuIn1d) while we reconsider our approach.

**Comment by e111077** [comment]
cc @allan-chen for next sync

**Comment by gullerya** [comment]
Ah, understood, thank you and yet, it would be nice to not require proactive `layoutOptions` call due the declarative flows of data binding which in this case becomes impossible.

Thanks again and it is up to you if to close the issue or keep it for the further tracking!
