### ISSUE TITLE
[mwc-menu] menu is not closed when document clicked

### ISSUE THREAD

**Issue by gullerya** [material-components/material-components-web-components#2356]
**Describe the bug**
In the pure simply plain HTML the body is not being stretched over the whole document, it is rather stay small and only extends as much as layouted elements in it.
When `mwc-menu` is opened in such a setup, clicking on most of the area of the viewport won't close the menu.

**To Reproduce**
1. Create simple HTML file
2. Import `mwc-menu`, set it with few list items and put in the body
3. Open menu
4. Click somewhere in the lower half of the screen
5. Observe that menu is not closed
6. Click somewhere at the top of the view
7. The menu closes as expected

**Expected behavior**
Menu should be closed on click wherever user clicks

Suggestion:
Now you are registering the `onBodyClick` in the `mwc-menu-surface` component on the `document.body`.
https://github.com/material-components/material-components-web-components/blob/5dd85d0c6700033fdc0da40d2424e9e8c46b0141/packages/menu/mwc-menu-surface-base.ts#L346

Do register it on the document instead.

**Comment by taylor-vann** [comment]
Hey @gullerya thanks for submitting and also thanks for writing some code!

Binding the event listener to the body is working as intended. 

The `<body>` element has a semantic function: it represents the content of an HTML document.

You may have noticed there is no `<document>` element? And that's because `document` is an interface that serves as an entry point into the web page's DOM Tree.

Technically, the `document` can listen for events just like how you've written, but it's more semantically correct to listen for events on the `<body>`.

I'd imagine clicking the lower half of the page does not close the menu on click because your `<body>` element does not occupy the entire document space.

You can accomplish this in CSS with something like below:

```css
html, body {
  min-hieght: 100%;
}
```

That way your `<body>` element will stretch across the document and a click will close the menu.

Hope it helps!

**Comment by gullerya** [comment]
I appreciate your response and woudn't like to push it any further, than just mentioning that the practice of listening on the top-level objects like `document` and / or `window` quite familiar to me from everywhere and actually even in this repo it is quite used - for example `dialog` implementation does it exactly as I did.

I'm definitely aware of a ways to stretch the `body` via CSS, but kinda documenting it in `menu` component would look like `menu` component's internal implementation is 'bleeding out' to the consumer realm, which usually better to avoid.

Thank you again!
