### ISSUE TITLE
Update demos

### ISSUE THREAD

**Issue by claytongulick** [material-components/material-components-web-components#237]
Currently starting several new projects and trying to determine which UI framework to use.

It's currently difficult to gauge where the new web components are, and whether they can be used in a new project (with the understanding that they are under development).

The best way to see that is on the demos page, linked to from the README, however, it doesn't look like that page has been updated in a while. Is there a way to get the demos page linked to from github updated so that it reflects the current status of the development of the components?

Alternately, is there a tracker page somewhere that says what components are "complete" and ready to use?

Thanks for the great work!!

**Comment by caliny97** [comment]
To project committers - Amazing work, thanks!!!
Lit-element is by far the best front-end framework I've used for web dev in my 20 years of experience, but without core UI components (buttons,tabs,dialogs, etc...) most of us would think it twice before using it in a big scale project. Although Iron/Paper elements can be used, people would ideally feel more comfortable using elements from the same family. I visit the project's page everyday hoping for all core components to be available. It would be great if expectations are set as to when all components would be ready. If it's 4 , 6 months or a year, it is what it is but at least people have a sense of timing.
Once again, thanks for the great work.

**Comment by rwestlund** [comment]
I second that. I was thinking they'd push this out with v1.0 on the eve of Google IO since the polymer team has done that before, but it doesn't look like it's that close to being ready. I have a big app in production that has one foot in lit-based elements and one foot in the old polymer-based paper elements. I'm also refreshing the npm search page every day hoping for more of these to be published. I can't express how eager I am to drop all the polymer compatibility stuff.

Would it help if we send you guys pizza and beer? ;)

**Comment by caliny97** [comment]
@project maintainers - great work, but please stop ignoring requests for project status and timelines.
Just sent an email to polymer-dev@googlegroups.com to see if we "the people" can get an update. Bcc'ed Sundar Pichai, maybe some connections might help move this project faster.
