### ISSUE TITLE
Material design vs Android/Flutter

### ISSUE THREAD

**Issue by jakearchibald** [material-components/material-components-web-components#2428]
This question came up in an I/O AMA, and this feels like the best place to ask it:

> I have noticed some of the Material Design controls in Chrome/Chrome OS system pages/apps look more like the Android/Flutter ones than the current state of Material Web Components; are there plans to unify those with Material Web Components or otherwise make them available to developers?

**Comment by e111077** [comment]
Heya Jake,

Chrome OS for most of their apps use MWC under the hood with some styling and some subclassing (just inspect the pages of their apps!). Their design team has their own set of design recommendations that deviate from Google Material spec, so that is why they have different feels.

Chrome itself, due to different application requirements, use the older Polymer paper-elements with quite a lot of styles applied to them.

Speaking to the team, they do not have any intentions to distribute their code to developers, but what they achieve is possible using MWC as that is how they develop their applications. Additionally, we are working with Chrome to improve MWCs API such that even Chrome OS won't have to subclass our components to theme them to their specifications

**Comment by jakearchibald** [comment]
Thank you!
