### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by jparish3** [material-components/material-components-web-components#30]
import {Fab} from "@material/mwc-fab" results in error:

Uncaught (in promise) TypeError: Failed to resolve module specifier "@material/mwc-fab". Relative references must start with either "/", "./", or "../".

**Comment by DominicWrege** [comment]
Did you try to import it like this:

```
import {Fab} from "@material/mwc-fab"
```
This will not work because the browser don’t support this syntax yet.

Try this:

```
import {Fab} from "./node_modules/@material/mwc-fab/mwc-fab.js"
```
Please read this:
However, since mwc-fab uses npm convention to reference dependencies by name, a light transform to rewrite specifiers to URLs is required to get it to run in the browser. The polymer-cli's development server polymer serve automatically handles this transform.

**Comment by azakus** [comment]
These packages are distributed with bare module specifiers because that is the most well supported by bundling tools like webpack and rollup. 
In the future, [ES Module Import Maps](https://wicg.github.io/import-maps/) are the proper platform way to set up the bare module specifiers to full paths.
