### ISSUE TITLE
Styling request: tab styling

### ISSUE THREAD

**Issue by samuelli** [material-components/material-components-web-components#324]
For `mwc-tab-bar` and it's relevant dependencies:
 * background color
 * active colors (ripple color, active)
 * indicator color
 * font color
 * font family
 * text transform
 * tab height

**Comment by samuelli** [comment]
For `<mwc-top-app-bar>`:
 * background color

**Comment by asyncLiz** [comment]
Closing since all of these properties are now customizable.

- background color: set `background-color` of `<mwc-tab-bar>`
- active colors (ripple color, active): `--mdc-theme-primary`
- indicator color: `--mdc-theme-primary`
- font color: `--mdc-theme-primary`
- font family: `--mdc-typography-font-family`
- text transform: `--mdc-typography-button-text-transform`
- tab height: `--mdc-tab-height`
