### ISSUE TITLE
No way to get textfield's value in an `@input` event

### ISSUE THREAD

**Issue by ashubham** [material-components/material-components-web-components#474]
**I'm submitting a:**

- [ ] bug report
- [x] feature request

**Current behavior:**

I can attach a `@input` event to `TextField`
```html
<mwc-textfield @input="${e => (No way to get textfield value here)}">
```

Doing a `e.target.value` above will give blank as the value is only updated on the `change` event internally in the Component.

**Expected behavior:**
```html
<mwc-textfield @input="${e => (Should have a way to get value here)}">
```

**Comment by jsilvermist** [comment]
What if you use `e.currentTarget.value`?

**Comment by Westbrook** [comment]
This is tricky, because for some reason the native `input` event of the included `input` element that powers `mwc-textfield` is `composed: true` by default, so it's not actually `mwc-textfield` that is dispatching this event. That means that while handling for `input` _should_ be added to the element, you can use the following workaround in the near term:
```
<mwc-textfield
    @input="${e => {
        const path = e.composedPath();
        const input = path[0];
        const value = input.value;
        // do stuff with the value.
    }}"
></mwc-textfield>
```
It's important to remember that the value you are working with here has yet to be commited to `mwc-textfield`, though hopefully changes to manage this will be submitted soon, but for the majority of things I can think of to do with this value (realtime validation, etc) you'll be in an OK place with this workaround.

**Comment by ashubham** [comment]
@Westbrook thanks, I am already using this workaround. `input` event by definition bubble out of the shadowRoot so that is expected. 

The right solution here would be `mwc-textfield` change the internal value of the `value` on `input` event instead of `change` event.

**Comment by azakus** [comment]
We may want to add a specific event for `change` in `mwc-textfield`, but the `input` event might be too high-frequency for us to provide an event.

@e111077 thoughts?

**Comment by e111077** [comment]
I thought input bubbles and was composed. Does lit not handle the event retargeting case?

**Comment by e111077** [comment]
I think it's a different issue that you may thinking. The issue is that on input event, the value of the component is not updated yet. I just want to take a look at performance implications before submitting it
