### ISSUE TITLE
Update scroll lock method

### ISSUE THREAD

**Issue by Sebastianhex** [material-components/material-components-web-components#475]
### I'm submitting a:
- [ ] bug report
- [x] feature request

### What OS are you using?
Windows 10

### What browser(s) is this affecting:
Chrome, Firefox, Opera, Edge, IE

### Current behaviour:
When opening a `<mwc-dialog>`, the current scroll lock method (adding `overflow: hidden;` to `<body>`) hides the body scroll bar, causing page content to shift.

**Example of content shifting:**
<img src="https://i.imgur.com/SQ3IRNr.gif">

### Expected behaviour:
Page content to not shift when locking body scroll.

**Example of content not shifting:**
<img src="https://i.imgur.com/ReJEcN8.gif">

**Comment by azakus** [comment]
This is caused by MDC's Foundation layer, and we don't want to deviate too heavily from their styling.

Having `overflow: hidden` to stop scrolling is a standard practice, and while it is unfortunate that it reflows layout with the scrollbar, we believe other solutions would be prohibitive to implement.
