### ISSUE TITLE
line length linting/formatting

### ISSUE THREAD

**Issue by 43081j** [material-components/material-components-web-components#478]
https://github.com/material-components/material-components-web-components/blob/2da5724c2bd18afeb35590a13c7d649d63ba8f20/packages/textfield/src/mwc-textfield-base.ts#L25

Out of interest, what's going on here? Shouldn't the linter or clang-format have picked lines like these up and separated them over multiple lines?

Maybe we have a bit of bad config somewhere, or is this expected? (i.e. column limit is that big..)

cc @e111077

**Comment by e111077** [comment]
seems like a weird config somewhere

**Comment by fernandopasik** [comment]
After running 
`eslint --print-config packages/textfield/src/mwc-textfield-base.ts`

I found that the config applied for the rule `max-len` is 
```
"max-len": [
  "off",
  {
    "code": 80,
    "tabWidth": 2,
    "ignoreUrls": true,
    "ignorePattern": "goog.(module|require)"
  }
],
```

**Comment by fernandopasik** [comment]
But the rule `max-len` is off in the repo eslint config
https://github.com/material-components/material-components-web-components/blob/master/.eslintrc.yaml#L29

**Comment by e111077** [comment]
Spoke to some of the Google TS style and readability people and there doesn't seem to be any consensus / guideline on the issue. I'm going to defer to clang-format's Google style which explicitly ignores line length for import files instead of eslint. I'd rather not have eslint and clang-format fight and internally we use tslint with slightly different rules, so I'd rather them not fight either.
