### ISSUE TITLE
Documentation error in `mwc-dialog`

### ISSUE THREAD

**Issue by johnthad** [material-components/material-components-web-components#608]
**I'm submitting a:**

- [x] bug report
- [ ] feature request

**Current behavior:**
The dialog titles do not appear in the demo.

**Expected behavior:**
The documentation describes `heading`. The actual property/attribute is `title`.

**Comment by aomarks** [comment]
Title was renamed to heading in https://github.com/material-components/material-components-web-components/pull/556, because it collided with the built-in title property. It's mentioned in the [CHANGELOG](https://github.com/material-components/material-components-web-components/blob/master/CHANGELOG.md), but we haven't done a release since that change. Sorry for the confusion, we should get a release out soon.
