### ISSUE TITLE
Slider: thumb-fill desync

### ISSUE THREAD

**Issue by jsejcksn** [material-components/material-components-web-components#673]
**I'm submitting a:**
- [x] bug report

**What OS are you using?**
macOS`10.15.1`

**What browser(s) is this bug affecting:**
Chrome`78.0.3904.108`

<details>
<summary>Additional software versions</summary>

```json
{
    "@emotion/core": "10.0.22",
    "@material/button": "4.0.0",
    "@material/icon-button": "4.0.0",
    "@material/ripple": "4.0.0",
    "@material/slider": "4.0.0",
    "@rmwc/button": "5.7.0",
    "@rmwc/icon-button": "5.7.0",
    "@rmwc/provider": "5.7.0",
    "@rmwc/ripple": "5.7.0",
    "@rmwc/slider": "5.7.0",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-scripts": "3.2.0"
  }
```
</details>

**Behavior:**
When
 - using a Slider with a controlled value, and
 - updating the controlling state value independently by two functions:
   - an external function, and
   - the `onInput` prop

the slider thumb position does not sync with the fill position.

**Steps to reproduce:**
Screen recording: https://imgur.com/a/rqxTPls (easter egg: audio)

**Related code:**
[CodeSandbox link](https://codesandbox.io/s/play-audio-file-v1joi?module=%2Fsrc%2Fcomponents%2FPlayer.js)

**Other information:**
I was redirected here. Additional details available at original issue: https://github.com/jamesmfriedman/rmwc/issues/524

**Comment by aomarks** [comment]
Are you actually using the Material Web Components (`<mwc-slider>`?) It looks like RMWC is probably using Material Components Web (yes our names are very confusing, sorry):

https://github.com/material-components/material-components-web-components (material components as native web components, this repo)

https://github.com/material-components/material-components-web (framework/api-neutral material design implementation, I think this is what RMWC is using).

Mind filing the issue here instead? https://github.com/material-components/material-components-web/issues

**Comment by jsejcksn** [comment]
@aomarks Oops—thanks. You can close this issue unless it's still needed.

**Comment by aomarks** [comment]
No problem, thanks for filing!
