### ISSUE TITLE
Option to hide arrows on number inputs

### ISSUE THREAD

**Issue by SketchBookkeeper** [material-components/material-components-web-components#701]
**I'm submitting a:**
- [ ] bug report
- [x] feature request

**What OS are you using?**
Windows 10

**What browser(s) is this bug affecting:**
Chrome, Firefox

**Current behavior:**
![number-input](https://user-images.githubusercontent.com/18709288/70821725-0cca2e80-1d99-11ea-8d6a-299b6a2c26de.png)
Firefox arrows ^

**Expected behavior:**
Add an option to apply css needed to hide arrows when input is set to `type='number'` since this option is not accessible due to the shadow dom.

**Comment by e111077** [comment]
Hello, number type is unfortunately not fully supported. Though, we will have a more-comprehensive styling option coming soon, so this may be fixed by that.

In the meantime, I recommend doing what `@material/mwc-textfield/mwc-textfield.js` is doing in your own file (import base class and styles) and add your own style to fix this. e.g.

```ts
import {customElement} from 'lit-element';
import {TextFieldBase} from './mwc-textfield-base.js';
import {style} from './mwc-textfield-css.js';

export {TextFieldType} from './mwc-textfield-base.js';

const hideInputSpinnerStyle = css`
  input[type=number]::-webkit-inner-spin-button {
    -webkit-appearance: none;
  }`

declare global {
  interface HTMLElementTagNameMap {
    'mwc-textfield': TextField;
  }
}

@customElement('mwc-textfield')
export class TextField extends TextFieldBase {
  static styles = [style, hideInputSpinnerStyle];
}

```

and import that file instead of the file that defines the `mwc-textfield` custom element

**Comment by SketchBookkeeper** [comment]
Thanks for looking into this for me.
