### ISSUE TITLE
mwc-select Outline label overlay with selected text

### ISSUE THREAD

**Issue by israelfloresdga** [material-components/material-components-web-components#883]
**I'm submitting a:**
- [x ] bug report
- [ ] feature request

**What OS are you using?**
Windows 10 
compilación 17763

**What browser(s) is this bug affecting:**
Firefox developer 74.0b4 (64-bit)
Microsoft Edge Versión 80.0.361.54 (Compilación oficial) (64 bits)

**Current behavior:**
I have a outlined select, when I click on it, the label translate itself to the top border, I select a option, then I click something else so the select lost focus, and the label move again inside the outline, so the label and the text of the selected value overlay.

**Expected behavior:**
If a value had been selected the label should stay at the top border

**Steps to reproduce:**

**Related code:**

```js
<mwc-select outlined .label="${this.labelSection}" naturalWidth @selected="${this._selected}">
```

**Comment by e111077** [comment]
Hello, this happens because there is no value set on the selected menu item despite there being `selectedText`. This is unfortunately a behavior of the [MDC](https://github.com/material-components/material-components-web/blob/master/packages/mdc-select/foundation.ts#L399) and would require an issue filed there instead.

For now, intended usage would be:

```html
<mwc-select>
  <mwc-list-item></mwc-list-item>
  <mwc-list-item value="non-empty">This will float the select since it has a value</mwc-list-item>
</mwc-select>
```

I will update the documentation accordingly
