### ISSUE TITLE
mwc-formfield allowing hyperlinks inside of label

### ISSUE THREAD

**Issue by elf-pavlik** [material-components/material-components-web-components#903]
**Is your feature request related to a problem? Please describe.**
Using `mwc-formfield` with `mwc-checkbox` in *"I accept [Terms of Service]() and [Privacy Policy]()"* scenarios

**Describe the solution you'd like**
Using either named slot or attribute to set label for `mwc-checkbox`

**Describe alternatives you've considered**
none

**Additional context**
example of checkbox label with links inside of it: https://hypothes.is/signup

![Screenshot_2020-02-20 Sign up for Hypothesis Hypothesis](https://user-images.githubusercontent.com/876431/74995213-d8689380-5415-11ea-9dfc-75fbc37366ba.png)

```html

  <input type="checkbox" class="form-checkbox__input" name="privacy_accepted" id="deformField5" value="true" required="">
  
    <label for="deformField5">
      I have read and agree to the <a class="link" href="https://web.hypothes.is/privacy/">privacy policy</a>, <a class="link" href="https://web.hypothes.is/terms-of-service/">terms of service</a>, and <a class="link" href="https://web.hypothes.is/community-guidelines/">community guidelines</a>.
    </label>
  ```

**Comment by elf-pavlik** [comment]
I just wanted to ask if that feature was already considered by project team. Thanks!

**Comment by asyncLiz** [comment]
This feature actually has been considered already and asked for internally (Googler context: b/111314020 yaqs/6488321546256384).

The main reason we are not supporting `<slot>` for labels in our components is because the burden of maintenance is increased on us to support more arbitrary use cases. For example, we would need to support hyperlink styling, touch targets, accessibility, and more just with this one UX.

Instead, our approach is to release baseline Material components that are extremely strict to spec, while allowing users to extend components and add additional custom or Material-inspired functionality on top of the baseline. 

See https://github.com/material-components/material-components-web-components/issues/602 for more details. That issue will be the one to track for this feature. I'll update it to mention labels.
